import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { CustoServicoInput, UsuarioPublico } from '@eduitsm/shared';
import { type FormEvent, useState } from 'react';
import { Layout } from '../components/layout.js';
import { api } from '../services/api.js';
import type { Servico } from './servicos-page.js';

interface Custo extends CustoServicoInput { id: string; servicoId: string; }
const dinheiro = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
export function CustosPage({ usuario, servicoId }: { usuario: UsuarioPublico; servicoId: string }) {
  const cache = useQueryClient(); const [rascunho, setRascunho] = useState<CustoServicoInput>({ tipo: 'OPEX', periodo: '', valorPrevisto: 0, valorRealizado: null });
  const servicos = useQuery({ queryKey: ['servicos'], queryFn: async () => (await api.get<Servico[]>('/servicos')).data }); const custos = useQuery({ queryKey: ['custos', servicoId], queryFn: async () => (await api.get<Custo[]>(`/servicos/${servicoId}/custos`)).data });
  const criar = useMutation({ mutationFn: async () => (await api.post<Custo>(`/servicos/${servicoId}/custos`, rascunho)).data, onSuccess: (custo) => { cache.setQueryData<Custo[]>(['custos', servicoId], (itens = []) => [...itens, custo]); setRascunho({ tipo: 'OPEX', periodo: '', valorPrevisto: 0, valorRealizado: null }); } });
  if (servicos.isLoading || custos.isLoading) return <Layout usuario={usuario} carregarOrganizacao><main className="page"><p role="status" className="state">Carregando custos e orçamento…</p></main></Layout>;
  if (servicos.isError || custos.isError) return <Layout usuario={usuario} carregarOrganizacao><main className="page"><div role="alert" className="alert error">⚠ Não foi possível carregar os custos. <button onClick={() => { servicos.refetch(); custos.refetch(); }}>Tentar novamente</button></div></main></Layout>;
  const lista = custos.data ?? []; const servico = servicos.data?.find((item) => item.id === servicoId);
  const totalPorTipo = (tipo: CustoServicoInput['tipo']) => lista.filter((custo) => custo.tipo === tipo).reduce((total, custo) => ({ previsto: total.previsto + (custo.valorPrevisto ?? 0), realizado: total.realizado + (custo.valorRealizado ?? 0) }), { previsto: 0, realizado: 0 });
  const capex = totalPorTipo('CAPEX'); const opex = totalPorTipo('OPEX');
  return <Layout usuario={usuario} carregarOrganizacao><main className="page"><h1>Custos e orçamento do serviço</h1><p className="subtitle">{servico?.nome ?? 'Serviço'}: investimento e custo operacional por período.</p>{criar.isError && <p role="alert" className="alert error">⚠ Não foi possível adicionar o lançamento. Verifique os valores.</p>}{criar.isSuccess && <p role="status" className="alert success">✓ Lançamento adicionado com sucesso.</p>}
    <section className="metrics" aria-label="Totais por natureza de custo"><article><small>CAPEX PREVISTO</small><strong>{dinheiro.format(capex.previsto)}</strong></article><article><small>CAPEX REALIZADO</small><strong>{dinheiro.format(capex.realizado)}</strong></article><article><small>OPEX PREVISTO</small><strong>{dinheiro.format(opex.previsto)}</strong></article><article><small>OPEX REALIZADO</small><strong>{dinheiro.format(opex.realizado)}</strong></article></section>
    {lista.length === 0 ? <p className="state empty-state">Nenhum lançamento de custo registrado.</p> : <div className="table-card"><table><thead><tr><th>Tipo</th><th>Período</th><th>Previsto</th><th>Realizado</th><th>Variação</th></tr></thead><tbody>{lista.map((custo) => <tr key={custo.id}><td><span className="pill">{custo.tipo}</span></td><td>{custo.periodo}</td><td>{dinheiro.format(custo.valorPrevisto ?? 0)}</td><td>{custo.valorRealizado == null ? '—' : dinheiro.format(custo.valorRealizado)}</td><td>{custo.valorRealizado == null ? '—' : dinheiro.format(custo.valorRealizado - (custo.valorPrevisto ?? 0))}</td></tr>)}</tbody></table></div>}
    <form className="domain-form" onSubmit={(event: FormEvent) => { event.preventDefault(); criar.mutate(); }}><h2>Novo lançamento</h2><label>Tipo<select value={rascunho.tipo} onChange={(event) => setRascunho({ ...rascunho, tipo: event.target.value as CustoServicoInput['tipo'] })}><option value="OPEX">OPEX</option><option value="CAPEX">CAPEX</option></select></label><label>Período<input required placeholder="AAAA-MM" value={rascunho.periodo} onChange={(event) => setRascunho({ ...rascunho, periodo: event.target.value })} /></label><label>Valor previsto<input required type="number" min="0" step="0.01" value={rascunho.valorPrevisto || ''} onChange={(event) => setRascunho({ ...rascunho, valorPrevisto: Number(event.target.value) })} /></label><label>Valor realizado<input type="number" min="0" step="0.01" value={rascunho.valorRealizado ?? ''} onChange={(event) => setRascunho({ ...rascunho, valorRealizado: event.target.value === '' ? null : Number(event.target.value) })} /></label><div className="form-actions"><button className="primary" disabled={criar.isPending}>{criar.isPending ? 'Adicionando…' : 'Adicionar lançamento'}</button></div></form>
  </main></Layout>;
}
