import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { DemandaCapacidadeInput, UsuarioPublico } from '@eduitsm/shared';
import { type FormEvent, useState } from 'react';
import { Layout } from '../components/layout.js';
import { api } from '../services/api.js';
import type { Servico } from './servicos-page.js';

interface Demanda extends DemandaCapacidadeInput { id: string; servicoId: string; }
export function DemandaPage({ usuario, servicoId }: { usuario: UsuarioPublico; servicoId: string }) {
  const cache = useQueryClient(); const [rascunho, setRascunho] = useState<DemandaCapacidadeInput>({ periodo: '', demandaPrevista: 0, capacidadeInstalada: 0, unidade: '' });
  const servicos = useQuery({ queryKey: ['servicos'], queryFn: async () => (await api.get<Servico[]>('/servicos')).data }); const demanda = useQuery({ queryKey: ['demanda', servicoId], queryFn: async () => (await api.get<Demanda[]>(`/servicos/${servicoId}/demanda`)).data });
  const criar = useMutation({ mutationFn: async () => (await api.post<Demanda>(`/servicos/${servicoId}/demanda`, rascunho)).data, onSuccess: (item) => { cache.setQueryData<Demanda[]>(['demanda', servicoId], (itens = []) => [...itens, item]); setRascunho({ periodo: '', demandaPrevista: 0, capacidadeInstalada: 0, unidade: '' }); } });
  if (servicos.isLoading || demanda.isLoading) return <Layout usuario={usuario} carregarOrganizacao><main className="page"><p role="status" className="state">Carregando demanda e capacidade…</p></main></Layout>;
  if (servicos.isError || demanda.isError) return <Layout usuario={usuario} carregarOrganizacao><main className="page"><div role="alert" className="alert error">⚠ Não foi possível carregar a demanda. <button onClick={() => { servicos.refetch(); demanda.refetch(); }}>Tentar novamente</button></div></main></Layout>;
  const lista = demanda.data ?? []; const servico = servicos.data?.find((item) => item.id === servicoId);
  return <Layout usuario={usuario} carregarOrganizacao><main className="page"><h1>Demanda e capacidade do serviço</h1><p className="subtitle">{servico?.nome ?? 'Serviço'}: demanda prevista e capacidade instalada por período.</p>{criar.isError && <p role="alert" className="alert error">⚠ Não foi possível adicionar o período. Verifique os valores.</p>}{criar.isSuccess && <p role="status" className="alert success">✓ Período adicionado com sucesso.</p>}
    {lista.length === 0 ? <p className="state empty-state">Nenhum período de demanda registrado.</p> : <div className="table-card"><table><thead><tr><th>Período</th><th>Demanda prevista</th><th>Capacidade instalada</th><th>Utilização</th><th>Situação</th></tr></thead><tbody>{lista.map((item) => { const semCapacidade = item.capacidadeInstalada === 0; const uso = semCapacidade ? 0 : Math.round(item.demandaPrevista / item.capacidadeInstalada * 100); const excedida = item.demandaPrevista > item.capacidadeInstalada; return <tr key={item.id}><td>{item.periodo}</td><td>{item.demandaPrevista} {item.unidade}</td><td>{item.capacidadeInstalada} {item.unidade}</td><td>{semCapacidade ? 'não calculável' : <><progress aria-label={`Utilização de ${item.periodo}`} max="100" value={Math.min(uso, 100)} /> {uso}%</>}</td><td><span className="pill">{semCapacidade ? 'Sem capacidade instalada' : excedida ? 'Capacidade excedida' : uso >= 90 ? 'Atenção' : 'Confortável'}</span></td></tr>; })}</tbody></table></div>}
    <form className="domain-form" onSubmit={(event: FormEvent) => { event.preventDefault(); criar.mutate(); }}><h2>Novo período</h2><label>Período<input required placeholder="AAAA-MM" value={rascunho.periodo} onChange={(event) => setRascunho({ ...rascunho, periodo: event.target.value })} /></label><label>Demanda prevista<input required type="number" min="0" step="1" value={rascunho.demandaPrevista || ''} onChange={(event) => setRascunho({ ...rascunho, demandaPrevista: Number(event.target.value) })} /></label><label>Capacidade instalada<input required type="number" min="0" step="1" value={rascunho.capacidadeInstalada || ''} onChange={(event) => setRascunho({ ...rascunho, capacidadeInstalada: Number(event.target.value) })} /></label><label>Unidade<input required maxLength={30} value={rascunho.unidade} onChange={(event) => setRascunho({ ...rascunho, unidade: event.target.value })} /></label><div className="form-actions"><button className="primary" disabled={criar.isPending}>{criar.isPending ? 'Adicionando…' : 'Adicionar período'}</button></div></form>
  </main></Layout>;
}
