import { useQuery } from '@tanstack/react-query';
import type { UsuarioPublico } from '@eduitsm/shared';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Layout } from '../components/layout.js';
import { api } from '../services/api.js';

interface PainelIndicador { periodo: string; cenarioId: string; cenario: { semente: number; perfil: string; periodoInicio: string; periodoFim: string; geradorVersao: string }; servicoId: string; nomeServico: string; indicadorId: string; nome: string; tipo: string; unidade: string; meta: number; sentido: 'MAIOR_MELHOR' | 'MENOR_MELHOR'; valor: number | null; denominador: number; evolucao: number | null; situacao: 'ABAIXO_DA_META' | 'NA_META' | 'ACIMA_DA_META' | null; medicoes: number; }
const rotuloSituacao = (situacao: Exclude<PainelIndicador['situacao'], null>) => ({ ABAIXO_DA_META: 'Abaixo da meta', NA_META: 'Na meta', ACIMA_DA_META: 'Acima da meta' })[situacao];
const rotuloEvolucao = (valor: number | null) => valor === null ? 'Sem período anterior comparável' : `Evolução: ${valor >= 0 ? '+' : ''}${valor}`;

export function IndicadoresPainelPage({ usuario }: { usuario: UsuarioPublico }) {
  const [servicoId, setServicoId] = useState(''); const [cenarioId, setCenarioId] = useState(''); const [periodo, setPeriodo] = useState('');
  const painel = useQuery({ queryKey: ['painel-indicadores', periodo], queryFn: async () => (await (periodo ? api.get<PainelIndicador[]>('/indicadores/painel', { params: { periodo } }) : api.get<PainelIndicador[]>('/indicadores/painel'))).data });
  if (painel.isLoading) return <Layout usuario={usuario} carregarOrganizacao><main className="page"><p role="status" className="state">Carregando painel de indicadores…</p></main></Layout>;
  if (painel.isError) return <Layout usuario={usuario} carregarOrganizacao><main className="page"><div role="alert" className="alert error">⚠ Não foi possível carregar o painel. <button onClick={() => painel.refetch()}>Tentar novamente</button></div></main></Layout>;
  const todos = painel.data ?? []; const servicos = [...new Map(todos.map((item) => [item.servicoId, item.nomeServico])).entries()]; const cenarios = [...new Map(todos.map((item) => [item.cenarioId, item.cenario])).entries()]; const itens = todos.filter((item) => (!servicoId || item.servicoId === servicoId) && (!cenarioId || item.cenarioId === cenarioId)); const abaixo = itens.filter((item) => item.situacao === 'ABAIXO_DA_META').length;
  return <Layout usuario={usuario} carregarOrganizacao><main className="page"><h1>Painel de indicadores</h1><p className="subtitle">Acompanhe os resultados calculados a partir das medições geradas pela simulação.</p>
    {todos.length === 0 ? <div className="state empty-state">Nenhuma medição simulada disponível. <Link to="/cenarios">Criar cenário de simulação</Link>.</div> : <>
      <div className="portfolio-toolbar"><label>Filtrar por serviço<select value={servicoId} onChange={(event) => setServicoId(event.target.value)}><option value="">Todos os serviços</option>{servicos.map(([id, nome]) => <option key={id} value={id}>{nome}</option>)}</select></label><label>Filtrar por cenário<select value={cenarioId} onChange={(event) => setCenarioId(event.target.value)}><option value="">Todos os cenários</option>{cenarios.map(([id, cenario]) => <option key={id} value={id}>Semente {cenario.semente} · {cenario.periodoInicio} a {cenario.periodoFim}</option>)}</select></label><label>Período de referência<input type="month" value={periodo} onChange={(event) => setPeriodo(event.target.value)} /></label></div>
      <p role="status" className="alert attention" aria-live="polite">{abaixo} de {itens.length} {itens.length === 1 ? 'indicador abaixo' : 'indicadores abaixo'} da meta{periodo ? ` no período de referência ${periodo}` : ''}.</p>
      {itens.length === 0 ? <p className="state empty-state">Nenhum indicador corresponde aos filtros selecionados.</p> : <div className="table-card"><table><thead><tr><th>Período e cenário</th><th>Serviço</th><th>Indicador</th><th>Resultado</th><th>Meta</th><th>Situação</th><th>Próximo passo</th></tr></thead><tbody>{itens.map((item) => <tr key={`${item.cenarioId}:${item.indicadorId}`}><td>{item.periodo}<small>Semente {item.cenario.semente} · {item.cenario.perfil} · gerador v{item.cenario.geradorVersao}</small></td><td>{item.nomeServico}</td><td>{item.nome}<small>{item.tipo} · base: {item.denominador} registros válidos · {rotuloEvolucao(item.evolucao)}{item.valor === null && (item.tipo === 'CUSTO' || item.tipo === 'RECEITA') ? ' · fonte operacional pendente' : ''}</small></td><td>{item.valor === null ? 'Sem medição' : `${item.valor} ${item.unidade}`}</td><td>{item.meta} {item.unidade} · {item.sentido === 'MAIOR_MELHOR' ? 'maior é melhor' : 'menor é melhor'}</td><td><span className="pill">{item.situacao === null ? 'Sem medição' : rotuloSituacao(item.situacao)}</span></td><td>{item.situacao === 'ABAIXO_DA_META' ? <Link to="/estrategia">Revisar estratégia</Link> : '—'}</td></tr>)}</tbody></table></div>}
    </>}
  </main></Layout>;
}
