import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { IndicadorInput, UsuarioPublico } from '@eduitsm/shared';
import { type FormEvent, useState } from 'react';
import { Layout } from '../components/layout.js';
import { api } from '../services/api.js';
import type { Servico } from './servicos-page.js';

interface Objetivo { id: string; codigo: string; descricao: string; }
interface Indicador extends Required<Omit<IndicadorInput, 'objetivoId'>> { id: string; servicoId: string; objetivoId: string | null; }
const tipos = { SLA: 'SLA', SATISFACAO: 'Satisfação', TEMPO_ATENDIMENTO: 'Tempo de atendimento', CUSTO: 'Custo', RECEITA: 'Receita' } as const;
const vazio: IndicadorInput = { nome: '', tipo: 'SLA', unidade: '', meta: 0, sentido: 'MAIOR_MELHOR', objetivoId: null };
const mensagemErro = (value: unknown) => typeof value === 'object' && value !== null && 'response' in value && typeof value.response === 'object' && value.response !== null && 'data' in value.response && typeof value.response.data === 'object' && value.response.data !== null && 'message' in value.response.data && typeof value.response.data.message === 'string' ? value.response.data.message : 'Não foi possível remover o indicador.';

export function IndicadoresPage({ usuario }: { usuario: UsuarioPublico }) {
  const cache = useQueryClient(); const [servicoId, setServicoId] = useState(''); const [rascunho, setRascunho] = useState<IndicadorInput>(vazio); const [editando, setEditando] = useState<string | null>(null); const [mensagem, setMensagem] = useState(''); const [erroRemocao, setErroRemocao] = useState('');
  const servicos = useQuery({ queryKey: ['servicos'], queryFn: async () => (await api.get<Servico[]>('/servicos')).data }); const objetivos = useQuery({ queryKey: ['objetivos'], queryFn: async () => (await api.get<Objetivo[]>('/objetivos')).data }); const selecionado = servicoId || servicos.data?.[0]?.id || ''; const indicadores = useQuery({ queryKey: ['indicadores', selecionado], queryFn: async () => (await api.get<Indicador[]>(`/servicos/${selecionado}/indicadores`)).data, enabled: Boolean(selecionado) });
  const salvar = useMutation({ mutationFn: async () => editando ? (await api.put<Indicador>(`/indicadores/${editando}`, rascunho)).data : (await api.post<Indicador>(`/servicos/${selecionado}/indicadores`, rascunho)).data, onMutate: () => { setMensagem(''); setErroRemocao(''); }, onSuccess: (indicador) => { cache.setQueryData<Indicador[]>(['indicadores', selecionado], (itens = []) => editando ? itens.map((item) => item.id === indicador.id ? indicador : item) : [...itens, indicador]); setRascunho(vazio); setEditando(null); setMensagem('Indicador salvo com sucesso.'); } });
  const remover = useMutation({ mutationFn: async (id: string) => api.delete(`/indicadores/${id}`), onMutate: () => { setMensagem(''); setErroRemocao(''); }, onSuccess: (_resposta, id) => { cache.setQueryData<Indicador[]>(['indicadores', selecionado], (itens = []) => itens.filter((item) => item.id !== id)); setMensagem('Indicador removido com sucesso.'); }, onError: (error) => setErroRemocao(mensagemErro(error)) });
  if (servicos.isLoading || objetivos.isLoading || indicadores.isLoading) return <Layout usuario={usuario} carregarOrganizacao><main className="page"><p role="status" className="state">Carregando indicadores…</p></main></Layout>;
  if (servicos.isError || objetivos.isError || indicadores.isError) return <Layout usuario={usuario} carregarOrganizacao><main className="page"><div role="alert" className="alert error">⚠ Não foi possível carregar os indicadores. <button onClick={() => { servicos.refetch(); objetivos.refetch(); indicadores.refetch(); }}>Tentar novamente</button></div></main></Layout>;
  const lista = indicadores.data ?? []; const objetivoNome = (id: string | null) => { const objetivo = objetivos.data?.find((item) => item.id === id); return objetivo ? objetivo.codigo : '—'; };
  return <Layout usuario={usuario} carregarOrganizacao><main className="page"><h1>Indicadores de desempenho do serviço <small className="tag">RF06</small></h1><p className="subtitle">Cada indicador exige meta e sentido; a avaliação abaixo ou acima da meta será apresentada após a simulação.</p>{salvar.isError && <p role="alert" className="alert error">⚠ Não foi possível salvar o indicador. Verifique os campos.</p>}{erroRemocao && <p role="alert" className="alert error">⚠ {erroRemocao}</p>}{mensagem && <p role="status" className="alert success">✓ {mensagem}</p>}
    <label className="service-picker">Serviço<select value={selecionado} onChange={(event) => { setServicoId(event.target.value); setEditando(null); setRascunho(vazio); }}>{(servicos.data ?? []).map((servico) => <option key={servico.id} value={servico.id}>{servico.nome}</option>)}</select></label>
    {lista.length === 0 ? <p className="state empty-state">Nenhum indicador definido.</p> : <div className="table-card"><table><thead><tr><th>Indicador</th><th>Tipo</th><th>Objetivo</th><th>Unidade</th><th>Meta</th><th>Sentido</th><th>Ações</th></tr></thead><tbody>{lista.map((indicador) => <tr key={indicador.id}><td>{indicador.nome}</td><td>{tipos[indicador.tipo]}</td><td>{objetivoNome(indicador.objetivoId)}</td><td>{indicador.unidade}</td><td>{indicador.meta}</td><td><span className="pill">{indicador.sentido === 'MAIOR_MELHOR' ? 'maior-melhor' : 'menor-melhor'}</span></td><td className="row-actions"><button type="button" onClick={() => { setEditando(indicador.id); setRascunho({ nome: indicador.nome, tipo: indicador.tipo, unidade: indicador.unidade, meta: indicador.meta, sentido: indicador.sentido, objetivoId: indicador.objetivoId }); }}>Editar {indicador.nome}</button><button type="button" aria-label={`Excluir ${indicador.nome}`} disabled={remover.isPending} onClick={() => remover.mutate(indicador.id)}>{remover.isPending ? 'Excluindo…' : `Excluir ${indicador.nome}`}</button></td></tr>)}</tbody></table></div>}
    <form className="domain-form" onSubmit={(event: FormEvent) => { event.preventDefault(); salvar.mutate(); }}><h2>{editando ? 'Editar indicador' : 'Novo indicador'}</h2><label>Nome do indicador<input required maxLength={120} value={rascunho.nome} onChange={(event) => setRascunho({ ...rascunho, nome: event.target.value })} /></label><label>Tipo<select value={rascunho.tipo} onChange={(event) => setRascunho({ ...rascunho, tipo: event.target.value as IndicadorInput['tipo'] })}>{Object.entries(tipos).map(([tipo, nome]) => <option key={tipo} value={tipo}>{nome}</option>)}</select></label><label>Objetivo vinculado<select value={rascunho.objetivoId ?? ''} onChange={(event) => setRascunho({ ...rascunho, objetivoId: event.target.value || null })}><option value="">Sem objetivo</option>{(objetivos.data ?? []).map((objetivo) => <option key={objetivo.id} value={objetivo.id}>{objetivo.codigo} · {objetivo.descricao}</option>)}</select></label><label>Unidade<input required maxLength={20} value={rascunho.unidade} onChange={(event) => setRascunho({ ...rascunho, unidade: event.target.value })} /></label><label>Meta<input required type="number" step="0.01" value={rascunho.meta || ''} onChange={(event) => setRascunho({ ...rascunho, meta: Number(event.target.value) })} /></label><label>Sentido<select value={rascunho.sentido} onChange={(event) => setRascunho({ ...rascunho, sentido: event.target.value as IndicadorInput['sentido'] })}><option value="MAIOR_MELHOR">Maior-melhor</option><option value="MENOR_MELHOR">Menor-melhor</option></select></label><div className="form-actions">{editando && <button type="button" onClick={() => { setEditando(null); setRascunho(vazio); }}>Cancelar edição</button>}<button className="primary" disabled={salvar.isPending || !selecionado}>{salvar.isPending ? 'Salvando…' : editando ? 'Salvar indicador' : 'Adicionar indicador'}</button></div></form>
  </main></Layout>;
}
