import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { ObjetivoInput, UsuarioPublico } from '@eduitsm/shared';
import { type FormEvent, useRef, useState } from 'react';
import { Layout } from '../components/layout.js';
import { api } from '../services/api.js';

interface ObjetivoResultado { id: string; organizacaoId: string; codigo: string; descricao: string; prazo: string | null; status: ObjetivoInput['status'] }
interface ObjetivoComCobertura extends ObjetivoResultado { servicosVinculados: number; cobertura: number }
const statusLabel = { ATIVO: 'Ativo', ATINGIDO: 'Atingido', CANCELADO: 'Cancelado' } as const;

export function ObjetivosPage({ usuario }: { usuario: UsuarioPublico }) {
  const cache = useQueryClient(); const [mensagem, setMensagem] = useState(''); const [editando, setEditando] = useState<string | null>(null); const formRef = useRef<HTMLFormElement>(null);
  const query = useQuery({ queryKey: ['objetivos'], queryFn: async () => {
    const objetivos = (await api.get<ObjetivoResultado[]>('/objetivos')).data;
    return Promise.all(objetivos.map(async (objetivo) => ({ ...objetivo, ...(await api.get<{ servicosVinculados: number; cobertura: number }>(`/objetivos/${objetivo.id}/cobertura`)).data })));
  } });
  const mutation = useMutation({ mutationFn: async (input: ObjetivoInput) => editando ? (await api.put<ObjetivoResultado>(`/objetivos/${editando}`, input)).data : (await api.post<ObjetivoResultado>('/objetivos', input)).data, onSuccess: (salvo) => { cache.setQueryData<ObjetivoComCobertura[]>(['objetivos'], (objetivos = []) => editando ? objetivos.map((objetivo) => objetivo.id === salvo.id ? { ...objetivo, ...salvo } : objetivo) : [...objetivos, { ...salvo, servicosVinculados: 0, cobertura: 0 }]); formRef.current?.reset(); setMensagem(editando ? 'Objetivo atualizado com sucesso.' : 'Objetivo adicionado com sucesso.'); setEditando(null); } });
  const exclusao = useMutation({ mutationFn: async (id: string) => api.delete(`/objetivos/${id}`), onSuccess: (_resultado, id) => { cache.setQueryData<ObjetivoComCobertura[]>(['objetivos'], (objetivos = []) => objetivos.filter((objetivo) => objetivo.id !== id)); setMensagem('Objetivo excluído com sucesso.'); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setMensagem(''); formRef.current = event.currentTarget; const form = new FormData(event.currentTarget); mutation.mutate({ codigo: String(form.get('codigo')), descricao: String(form.get('descricao')), prazo: String(form.get('prazo')) || null, status: String(form.get('status')) as ObjetivoInput['status'] }); };
  if (query.isLoading) return <Layout usuario={usuario} carregarOrganizacao><main className="page"><p role="status" className="state">Carregando objetivos…</p></main></Layout>;
  if (query.isError) return <Layout usuario={usuario} carregarOrganizacao><main className="page"><div role="alert" className="alert error">⚠ Não foi possível carregar os objetivos. <button onClick={() => query.refetch()}>Tentar novamente</button></div></main></Layout>;
  const objetivos = query.data ?? [];
  const prepararEdicao = (objetivo: ObjetivoComCobertura) => { setEditando(objetivo.id); const campos = formRef.current?.elements; if (!campos) return; (campos.namedItem('codigo') as HTMLInputElement).value = objetivo.codigo; (campos.namedItem('descricao') as HTMLTextAreaElement).value = objetivo.descricao; (campos.namedItem('prazo') as HTMLInputElement).value = objetivo.prazo?.slice(0, 10) ?? ''; (campos.namedItem('status') as HTMLSelectElement).value = objetivo.status; };
  return <Layout usuario={usuario} carregarOrganizacao><main className="page"><h1>Objetivos estratégicos do negócio <small className="tag">RF04</small></h1><p className="subtitle">A cobertura soma as contribuições dos serviços vinculados e nunca ultrapassa 100%.</p>
    {mensagem && <p role="status" className="alert success">✓ {mensagem}</p>}{mutation.isError && <p role="alert" className="alert error">⚠ Não foi possível {editando ? 'salvar' : 'adicionar'} o objetivo. Verifique o código e os demais campos.</p>}{exclusao.isError && <p role="alert" className="alert error">⚠ Não foi possível excluir o objetivo. Remova vínculos e indicadores antes de tentar novamente.</p>}
    {objetivos.length === 0 ? <p className="state empty-state">Nenhum objetivo estratégico cadastrado.</p> : <div className="table-card"><table><thead><tr><th>Código</th><th>Descrição do objetivo</th><th>Prazo</th><th>Status</th><th>Serviços</th><th>Cobertura</th><th>Ações</th></tr></thead><tbody>{objetivos.map((objetivo) => <tr key={objetivo.id}><td><strong>{objetivo.codigo}</strong></td><td>{objetivo.descricao}</td><td>{objetivo.prazo ? new Date(objetivo.prazo).toLocaleDateString('pt-BR', { month: 'short', year: 'numeric', timeZone: 'UTC' }) : '—'}</td><td><span className="pill">{statusLabel[objetivo.status]}</span></td><td>{objetivo.servicosVinculados} {objetivo.servicosVinculados === 1 ? 'serviço' : 'serviços'}</td><td><progress aria-label={`Cobertura de ${objetivo.codigo}`} max="100" value={objetivo.cobertura} /> <strong>{objetivo.cobertura}%</strong></td><td className="row-actions"><button type="button" onClick={() => prepararEdicao(objetivo)}>Editar {objetivo.codigo}</button><button type="button" disabled={exclusao.isPending} onClick={() => exclusao.mutate(objetivo.id)}>Excluir {objetivo.codigo}</button></td></tr>)}</tbody></table></div>}
    <form ref={formRef} className="domain-form" aria-label="Formulário de objetivo estratégico" onSubmit={submit}><h2>{editando ? 'Editar objetivo estratégico' : 'Novo objetivo estratégico'}</h2><label>Código<input name="codigo" maxLength={20} required /></label><label>Status<select name="status" defaultValue="ATIVO"><option value="ATIVO">Ativo</option><option value="ATINGIDO">Atingido</option><option value="CANCELADO">Cancelado</option></select></label><label>Prazo<input name="prazo" type="date" /></label><label className="full-field">Descrição<textarea name="descricao" maxLength={1000} required /></label><div className="form-actions">{editando && <button type="button" onClick={() => { formRef.current?.reset(); setEditando(null); }}>Cancelar edição</button>}<button type="reset">Limpar</button><button className="primary" disabled={mutation.isPending}>{mutation.isPending ? 'Salvando…' : editando ? 'Salvar objetivo' : 'Adicionar objetivo'}</button></div></form>
  </main></Layout>;
}
