import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { ServicoInput, UsuarioPublico } from '@eduitsm/shared';
import { type FormEvent, useState } from 'react';
import { Link } from 'react-router-dom';
import { Layout } from '../components/layout.js';
import { api } from '../services/api.js';

export interface Servico { id: string; organizacaoId: string; nome: string; descricao: string | null; publicoAlvo: string | null; status: ServicoInput['status']; criadoEm: string; }
const vazio: ServicoInput = { nome: '', descricao: null, publicoAlvo: null, status: 'PROPOSTO' };
const rotulo = { PROPOSTO: 'Proposto', EM_DESENHO: 'Em desenho', EM_OPERACAO: 'Em operação', DESCONTINUADO: 'Descontinuado' } as const;
const erro = (value: unknown, fallback: string) => typeof value === 'object' && value !== null && 'response' in value && typeof value.response === 'object' && value.response !== null && 'data' in value.response && typeof value.response.data === 'object' && value.response.data !== null && 'message' in value.response.data && typeof value.response.data.message === 'string' ? value.response.data.message : fallback;

export function ServicosPage({ usuario }: { usuario: UsuarioPublico }) {
  const cache = useQueryClient(); const [filtro, setFiltro] = useState<'TODOS' | ServicoInput['status']>('TODOS'); const [rascunho, setRascunho] = useState<ServicoInput>(vazio); const [editando, setEditando] = useState<string | null>(null); const [mensagem, setMensagem] = useState('');
  const query = useQuery({ queryKey: ['servicos'], queryFn: async () => (await api.get<Servico[]>('/servicos')).data });
  const salvar = useMutation({ mutationFn: async () => editando ? (await api.put<Servico>(`/servicos/${editando}`, rascunho)).data : (await api.post<Servico>('/servicos', rascunho)).data, onSuccess: (servico) => { cache.setQueryData<Servico[]>(['servicos'], (itens = []) => editando ? itens.map((item) => item.id === servico.id ? servico : item) : [...itens, servico]); setMensagem(editando ? 'Serviço atualizado com sucesso.' : 'Serviço adicionado com sucesso.'); setRascunho(vazio); setEditando(null); } });
  const excluir = useMutation({ mutationFn: async (id: string) => api.delete(`/servicos/${id}`), onSuccess: (_resultado, id) => { cache.setQueryData<Servico[]>(['servicos'], (itens = []) => itens.filter((item) => item.id !== id)); setMensagem('Serviço excluído com sucesso.'); } });
  if (query.isLoading) return <Layout usuario={usuario} carregarOrganizacao><main className="page"><p role="status" className="state">Carregando portfólio de serviços…</p></main></Layout>;
  if (query.isError) return <Layout usuario={usuario} carregarOrganizacao><main className="page"><div role="alert" className="alert error">⚠ Não foi possível carregar o portfólio. <button onClick={() => query.refetch()}>Tentar novamente</button></div></main></Layout>;
  const servicos = query.data ?? []; const exibidos = filtro === 'TODOS' ? servicos : servicos.filter((servico) => servico.status === filtro);
  const submit = (event: FormEvent) => { event.preventDefault(); setMensagem(''); salvar.mutate(); };
  return <Layout usuario={usuario} carregarOrganizacao><main className="page"><h1>Portfólio de serviços de TI</h1><p className="subtitle">Serviços oferecidos pela organização, com custo, demanda e situação de alinhamento estratégico.</p>
    {mensagem && <p role="status" className="alert success">✓ {mensagem}</p>}{(salvar.isError || excluir.isError) && <p role="alert" className="alert error">⚠ {salvar.isError ? erro(salvar.error, 'Não foi possível salvar o serviço.') : erro(excluir.error, 'Não foi possível excluir o serviço.')}</p>}
    <div className="portfolio-toolbar"><label>Filtrar por status<select aria-label="Filtrar por status" value={filtro} onChange={(event) => setFiltro(event.target.value as typeof filtro)}><option value="TODOS">Todos</option>{Object.entries(rotulo).map(([status, label]) => <option key={status} value={status}>{label}</option>)}</select></label><button type="button" className="primary" onClick={() => { setEditando(null); setRascunho(vazio); }}>Novo serviço</button></div>
    {exibidos.length === 0 ? <p className="state empty-state">Nenhum serviço neste filtro.</p> : <div className="table-card"><table><thead><tr><th>Serviço</th><th>Status no ciclo de vida</th><th>Público-alvo</th><th>Ações</th></tr></thead><tbody>{exibidos.map((servico) => <tr key={servico.id}><td><strong>{servico.nome}</strong><br /><small>{servico.descricao ?? 'Sem descrição'}</small></td><td><span className="pill">{rotulo[servico.status]}</span></td><td>{servico.publicoAlvo ?? '—'}</td><td className="row-actions"><Link to={`/servicos/${servico.id}/custos`} aria-label={`Custos de ${servico.nome}`}>Custos</Link><Link to={`/servicos/${servico.id}/demanda`} aria-label={`Demanda de ${servico.nome}`}>Demanda</Link><button type="button" onClick={() => { setEditando(servico.id); setRascunho({ nome: servico.nome, descricao: servico.descricao, publicoAlvo: servico.publicoAlvo, status: servico.status }); }}>Editar {servico.nome}</button><button type="button" onClick={() => excluir.mutate(servico.id)}>Excluir {servico.nome}</button></td></tr>)}</tbody></table></div>}
    <form id="form-servico" className="domain-form" aria-label="Formulário de serviço" onSubmit={submit}><h2>{editando ? 'Cadastro do serviço de TI' : 'Novo serviço'}</h2><label>Nome do serviço<input required maxLength={120} value={rascunho.nome} onChange={(event) => setRascunho({ ...rascunho, nome: event.target.value })} /></label><label>Status no ciclo de vida<select value={rascunho.status} onChange={(event) => setRascunho({ ...rascunho, status: event.target.value as ServicoInput['status'] })}>{Object.entries(rotulo).map(([status, label]) => <option key={status} value={status}>{label}</option>)}</select></label><label className="full-field">Descrição<textarea maxLength={4000} value={rascunho.descricao ?? ''} onChange={(event) => setRascunho({ ...rascunho, descricao: event.target.value || null })} /></label><label>Público-alvo<input maxLength={120} value={rascunho.publicoAlvo ?? ''} onChange={(event) => setRascunho({ ...rascunho, publicoAlvo: event.target.value || null })} /></label><div className="form-actions">{editando && <button type="button" onClick={() => { setEditando(null); setRascunho(vazio); }}>Cancelar edição</button>}<button className="primary" disabled={salvar.isPending}>{salvar.isPending ? 'Salvando…' : 'Salvar serviço'}</button></div></form>
  </main></Layout>;
}
