import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { VinculoEstrategicoInput, UsuarioPublico } from '@eduitsm/shared';
import { type FormEvent, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Layout } from '../components/layout.js';
import { api } from '../services/api.js';
import type { Servico } from './servicos-page.js';

interface Objetivo { id: string; codigo: string; descricao: string; }
interface IndicadorParaVinculo { id: string; servicoId: string; objetivoId: string | null; nome: string; tipo: string; unidade: string; }
interface Vinculo extends VinculoEstrategicoInput { id: string; indicador?: Pick<IndicadorParaVinculo, 'id' | 'nome' | 'tipo' | 'unidade'> | null; }
interface EstadoDeRetorno { vinculoDraft?: { justificativaValor: string; contribuicao: number; servicoId: string; objetivoId: string; indicadorId: string; }; }
const mensagemErro = (value: unknown) => typeof value === 'object' && value !== null && 'response' in value && typeof value.response === 'object' && value.response !== null && 'data' in value.response && typeof value.response.data === 'object' && value.response.data !== null && 'message' in value.response.data && typeof value.response.data.message === 'string' ? value.response.data.message : 'Não foi possível salvar o vínculo.';

export function VinculosPage({ usuario }: { usuario: UsuarioPublico }) {
  const cache = useQueryClient(); const retorno = useLocation().state as EstadoDeRetorno | null; const [rascunho, setRascunho] = useState(() => retorno?.vinculoDraft ?? { justificativaValor: '', contribuicao: 0, servicoId: '', objetivoId: '', indicadorId: '' }); const [mensagem, setMensagem] = useState(''); const [erroRemocao, setErroRemocao] = useState('');
  const servicos = useQuery({ queryKey: ['servicos'], queryFn: async () => (await api.get<Servico[]>('/servicos')).data }); const objetivos = useQuery({ queryKey: ['objetivos'], queryFn: async () => (await api.get<Objetivo[]>('/objetivos')).data }); const vinculos = useQuery({ queryKey: ['vinculos'], queryFn: async () => (await api.get<Vinculo[]>('/vinculos')).data }); const pendencias = useQuery({ queryKey: ['vinculos', 'pendencias'], queryFn: async () => (await api.get<Servico[]>('/vinculos/pendencias')).data });
  const servicoSelecionado = rascunho.servicoId || servicos.data?.[0]?.id || '';
  const objetivoSelecionado = rascunho.objetivoId || objetivos.data?.[0]?.id || '';
  const indicadores = useQuery({ queryKey: ['indicadores', servicoSelecionado], queryFn: async () => (await api.get<IndicadorParaVinculo[]>(`/servicos/${servicoSelecionado}/indicadores`)).data, enabled: Boolean(servicoSelecionado) });
  const criar = useMutation({ mutationFn: async () => (await api.post<Vinculo>('/vinculos', { justificativaValor: rascunho.justificativaValor, contribuicao: rascunho.contribuicao, servicoId: servicoSelecionado, objetivoId: objetivoSelecionado, indicadorId: rascunho.indicadorId || null })).data, onMutate: () => { setMensagem(''); setErroRemocao(''); }, onSuccess: (vinculo) => { cache.setQueryData<Vinculo[]>(['vinculos'], (itens = []) => [...itens, vinculo]); cache.invalidateQueries({ queryKey: ['vinculos', 'pendencias'] }); setRascunho({ justificativaValor: '', contribuicao: 0, servicoId: '', objetivoId: '', indicadorId: '' }); setMensagem('Vínculo salvo com sucesso.'); } });
  const remover = useMutation({ mutationFn: async (id: string) => api.delete(`/vinculos/${id}`), onMutate: () => { setMensagem(''); setErroRemocao(''); }, onSuccess: (_resposta, id) => { cache.setQueryData<Vinculo[]>(['vinculos'], (itens = []) => itens.filter((item) => item.id !== id)); cache.invalidateQueries({ queryKey: ['vinculos', 'pendencias'] }); setMensagem('Vínculo removido com sucesso.'); }, onError: (error) => setErroRemocao(mensagemErro(error)) });
  if (servicos.isLoading || objetivos.isLoading || vinculos.isLoading || pendencias.isLoading || indicadores.isLoading) return <Layout usuario={usuario} carregarOrganizacao><main className="page"><p role="status" className="state">Carregando vínculos estratégicos…</p></main></Layout>;
  if (servicos.isError || objetivos.isError || vinculos.isError || pendencias.isError || indicadores.isError) return <Layout usuario={usuario} carregarOrganizacao><main className="page"><div role="alert" className="alert error">⚠ Não foi possível carregar os vínculos. <button onClick={() => { servicos.refetch(); objetivos.refetch(); vinculos.refetch(); pendencias.refetch(); indicadores.refetch(); }}>Tentar novamente</button></div></main></Layout>;
  const lista = vinculos.data ?? []; const nomeServico = (id: string) => servicos.data?.find((item) => item.id === id)?.nome ?? id; const nomeObjetivo = (id: string) => { const objetivo = objetivos.data?.find((item) => item.id === id); return objetivo ? `${objetivo.codigo} · ${objetivo.descricao}` : id; };
  const indicadoresCompativeis = (indicadores.data ?? []).filter((indicador) => !indicador.objetivoId || indicador.objetivoId === objetivoSelecionado);
  return <Layout usuario={usuario} carregarOrganizacao><main className="page"><h1>Vínculo entre serviço e objetivo estratégico <small className="tag">RF04</small></h1><p className="subtitle">Demonstre explicitamente como cada serviço de TI gera valor para um objetivo do negócio.</p>{criar.isError && <p role="alert" className="alert error">⚠ {mensagemErro(criar.error)}</p>}{erroRemocao && <p role="alert" className="alert error">⚠ {erroRemocao}</p>}{mensagem && <p role="status" className="alert success">✓ {mensagem}</p>}
    {(pendencias.data ?? []).length > 0 && <div className="alert attention"><strong>Serviços sem vínculo estratégico:</strong> {(pendencias.data ?? []).map((servico) => servico.nome).join(', ')}.</div>}
    <form className="domain-form" onSubmit={(event: FormEvent) => { event.preventDefault(); criar.mutate(); }}><h2>Novo vínculo estratégico</h2><label>Serviço de TI<select value={servicoSelecionado} onChange={(event) => setRascunho({ ...rascunho, servicoId: event.target.value, indicadorId: '' })}>{(servicos.data ?? []).map((servico) => <option key={servico.id} value={servico.id}>{servico.nome}</option>)}</select></label><label>Objetivo estratégico do negócio<select value={objetivoSelecionado} onChange={(event) => setRascunho({ ...rascunho, objetivoId: event.target.value, indicadorId: '' })}>{(objetivos.data ?? []).map((objetivo) => <option key={objetivo.id} value={objetivo.id}>{objetivo.codigo} · {objetivo.descricao}</option>)}</select></label><label>Indicador que demonstra a contribuição<select value={rascunho.indicadorId} onChange={(event) => setRascunho({ ...rascunho, indicadorId: event.target.value })}><option value="">Ainda não definido</option>{indicadoresCompativeis.map((indicador) => <option key={indicador.id} value={indicador.id}>{indicador.nome} ({indicador.tipo})</option>)}</select></label>{indicadoresCompativeis.length === 0 && <p className="state">Nenhum indicador compatível. <Link to="/indicadores" state={{ contextoVinculo: { rascunho, servicoId: servicoSelecionado, objetivoId: objetivoSelecionado } }}>Criar indicador para este serviço</Link>.</p>}<label className="full-field">Justificativa de valor<textarea required maxLength={2000} value={rascunho.justificativaValor} onChange={(event) => setRascunho({ ...rascunho, justificativaValor: event.target.value })} /></label><label>Contribuição estimada<input required type="number" min="0.01" max="100" step="0.01" value={rascunho.contribuicao || ''} onChange={(event) => setRascunho({ ...rascunho, contribuicao: Number(event.target.value) })} /></label><div className="form-actions"><button className="primary" disabled={criar.isPending || !servicos.data?.length || !objetivos.data?.length}>{criar.isPending ? 'Salvando…' : 'Salvar vínculo'}</button></div></form>
    <section className="table-card"><h2>Vínculos já registrados</h2>{lista.length === 0 ? <p className="state">Nenhum vínculo registrado.</p> : <table><thead><tr><th>Serviço</th><th>Objetivo</th><th>Indicador</th><th>Contribuição</th><th>Ação</th></tr></thead><tbody>{lista.map((vinculo) => <tr key={vinculo.id}><td>{nomeServico(vinculo.servicoId)}</td><td>{nomeObjetivo(vinculo.objetivoId)}</td><td>{vinculo.indicador ? `Indicador: ${vinculo.indicador.nome} (${vinculo.indicador.tipo})` : 'Não informado'}</td><td><span className="pill">{vinculo.contribuicao}%</span></td><td><button type="button" aria-label="Remover vínculo" disabled={remover.isPending} onClick={() => remover.mutate(vinculo.id)}>{remover.isPending ? 'Removendo…' : 'Remover vínculo'}</button></td></tr>)}</tbody></table>}</section>
  </main></Layout>;
}
